
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 28 23:51:07 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 35;
  public static final int CONST = 10;
  public static final int NAMESPACE = 4;
  public static final int GRT = 28;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int CONTINUE = 18;
  public static final int LSS = 30;
  public static final int FOR = 19;
  public static final int MINUS = 22;
  public static final int RPAREN = 42;
  public static final int STATIC = 20;
  public static final int COMMA = 39;
  public static final int CLASS = 8;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int IF = 11;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 36;
  public static final int RETURN = 15;
  public static final int EQUAL = 26;
  public static final int GRTE = 29;
  public static final int LAMBDA = 45;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int BITOR = 33;
  public static final int MUL = 23;
  public static final int MOD = 25;
  public static final int BREAK = 7;
  public static final int IDENT = 3;
  public static final int VOID = 16;
  public static final int COLON = 38;
  public static final int LBRACE = 5;
  public static final int ELSE = 9;
  public static final int LSQUARE = 43;
  public static final int READ = 14;
  public static final int CHARCONST = 47;
  public static final int RSQUARE = 44;
  public static final int LSSE = 31;
  public static final int RBRACE = 6;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int BITAND = 32;
  public static final int PRINT = 13;
}

