
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 11 10:52:27 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 34;
  public static final int CONST = 9;
  public static final int NAMESPACE = 3;
  public static final int GRT = 27;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 26;
  public static final int LPAREN = 40;
  public static final int SEMI = 36;
  public static final int CONTINUE = 17;
  public static final int LSS = 29;
  public static final int FOR = 18;
  public static final int MINUS = 21;
  public static final int RPAREN = 41;
  public static final int STATIC = 19;
  public static final int COMMA = 38;
  public static final int CLASS = 7;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int ASSIGN = 33;
  public static final int IF = 10;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 35;
  public static final int RETURN = 14;
  public static final int EQUAL = 25;
  public static final int GRTE = 28;
  public static final int LAMBDA = 44;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int BITOR = 32;
  public static final int MUL = 22;
  public static final int MOD = 24;
  public static final int IDENT = 45;
  public static final int BREAK = 6;
  public static final int VOID = 15;
  public static final int COLON = 37;
  public static final int LBRACE = 4;
  public static final int ELSE = 8;
  public static final int LSQUARE = 42;
  public static final int READ = 13;
  public static final int CHARCONST = 48;
  public static final int RSQUARE = 43;
  public static final int LSSE = 30;
  public static final int RBRACE = 5;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int BITAND = 31;
  public static final int PRINT = 12;
}

